### ISSUE TITLE
Will this work at the very first time when successful invokes or just work approaching the E5 subscription expiring time?

### ISSUE THREAD

**Issue by ratingeater** [QuiltMeow/KeepAliveE5#3]
Cause I successfully invoked but the expiring time remains still

**Comment by yhzcake** [comment]
i have same question. actually, Microsoft set the client secret up to two years, but register_apps_by_force.sh set to 100.
I don't know if it's going to work

**Comment by ratingeater** [comment]
> i have same question. actually, Microsoft set the client secret up to two years, but register_apps_by_force.sh set to 100. I don't know if it's going to work

It seems that it works 1 month before expiring
